In [1]:
import pandas as pd

import statbotics

sb = statbotics.Statbotics()

In [2]:
pd.DataFrame(sb.get_team_years(year=2023, metric="epa_diff", limit=10, fields=["team", "name", "epa_start", "epa_end", "epa_diff", "total_epa_rank"]))

,team,name,epa_start,epa_end,epa_diff,total_epa_rank
0,695,Bison Robotics,24.48,60.86,36.38,6
1,3005,RoboChargers,31.50,63.47,31.97,4
2,5472,Stallion Robotics: The Wyld Stallyns,25.46,54.84,29.38,20
3,5232,Talons,19.85,48.03,28.18,50
4,4422,Twisted Angels,17.11,45.25,28.14,67
5,2056,OP Robotics,50.31,78.25,27.94,1
6,7627,Bearcat Robotics,16.20,43.10,26.90,95
7,3467,Windham Windup,30.30,56.96,26.66,13
8,359,Hawaiian Kids,28.97,55.37,26.40,17
9,2539,Krypton Cougars,30.16,55.68,25.52,15